spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/locusc1
        username: root
        password: root
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/locusc2
        username: root
        password: root
    sharding:
      tables:
        city:
          database-strategy:
            hint:
              algorithm-class-name: cn.locusc.sharding.sphere.jdbc.hint.CustomHintShardingAlgorithm
