spring:
  shardingsphere:
    datasource:
      names: master,slave0
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url:jdbc: mysql://localhost:3306/locusc1
        username: root
        password: root
      slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/locusc2
        username: root
        password: root
    masterslave:
      name: datasource
      master-data-source-name: master
      slave-data-source-names: slave0
      load-balance-algorithm-type: ROUND_ROBIN
    sharding:
      tables:
        city:
          key-generator:
            column: id
            type: SNOWFLAKE
